port: 8080
firestore:
  project_id: lumos-profile-dev
  credentials: ../secrets/cred.json
line:
  channel_id: "2009118669"
  channel_secret: "28a89a959f3bf4d3993a8c559f4bc6a0"
  redirect_uri: "http://localhost:8080/api/line-oauth"
  state: ""
