port: 8080
firestore:
  project_id: lumos-profile-dev
  credentials: ../secrets/cred.json
line:
  channel_id: "YOUR_LINE_CHANNEL_ID"
  channel_secret: "YOUR_LINE_CHANNEL_SECRET"
  redirect_uri: "http://localhost:8080/api/line-oauth"
  state: ""
